CREATE TABLE [dbo].[IndexStats]
(
    [pass] [tinyint] NULL,
	[sample_time] [datetimeoffset](7) NULL,
	[server_name] [varchar](50) NULL,
    [database_id] [int] NULL,
    [database_name] [varchar](30) NULL,
    [object_id] [int] NULL,
    [index_id] [int] NULL,
    [index_type] [int] NULL,
    [schema_name] [varchar](30) NULL,
    [object_name] [varchar](150) NULL,
    [index_name] [varchar](1000) NULL,
    [object_type] [varchar](10) NULL,
    [rows] [bigint] NULL,
    [is_unique] [bit] NULL,
    [is_primary_key] [bit] NULL,
    [is_XML] [bit] NULL,
    [is_spatial] [bit] NULL,
    [is_NC_columnstore] [bit] NULL,
    [is_CX_columnstore] [bit] NULL,
    [is_in_memory_oltp] [bit] NULL,
    [is_disabled] [bit] NULL,
    [is_hypothetical] [bit] NULL,
    [is_padded] [bit] NULL,
    [fill_factor] [tinyint] NULL,
    [filter_definition] [nvarchar](max) NULL,
    [user_seeks] [bigint] NULL,
    [user_scans] [bigint] NULL,
    [user_lookups] [bigint] NULL,
    [user_updates] [bigint] NULL,
    [last_user_seek] [datetime] NULL,
    [last_user_scan] [datetime] NULL,
    [last_user_lookup] [datetime] NULL,
    [last_user_update] [datetime] NULL,
    [create_date] [datetime] NULL,
    [modify_date] [datetime] NULL,
    INDEX IX_pass NONCLUSTERED (
        [pass]
    )
)